# Generated by Django 3.0.3 on 2020-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('bday', models.DateField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
